// generated by src/lib/action_collections.gen.ts - DO NOT EDIT OR RISK LOST DATA

import type {ActionSpecUnion} from '@fuzdev/fuz_app/actions/action_spec.js';
import * as specs from './action_specs.js';
import {z} from 'zod';
import type {
	ActionEventLocalCallData,
	ActionEventRemoteNotificationData,
	ActionEventRequestResponseData,
} from '@fuzdev/fuz_app/actions/action_event_data.js';

/**
 * Action specifications indexed by method name.
 * These represent the complete action spec definitions.
 */
export const ActionSpecs = {
	heartbeat: specs.heartbeat_action_spec,
	cancel: specs.cancel_action_spec,
	ping: specs.ping_action_spec,
	session_load: specs.session_load_action_spec,
	filer_change: specs.filer_change_action_spec,
	diskfile_update: specs.diskfile_update_action_spec,
	diskfile_delete: specs.diskfile_delete_action_spec,
	directory_create: specs.directory_create_action_spec,
	completion_create: specs.completion_create_action_spec,
	completion_progress: specs.completion_progress_action_spec,
	toggle_main_menu: specs.toggle_main_menu_action_spec,
	provider_load_status: specs.provider_load_status_action_spec,
	provider_update_api_key: specs.provider_update_api_key_action_spec,
	terminal_create: specs.terminal_create_action_spec,
	terminal_data_send: specs.terminal_data_send_action_spec,
	terminal_data: specs.terminal_data_action_spec,
	terminal_resize: specs.terminal_resize_action_spec,
	terminal_close: specs.terminal_close_action_spec,
	terminal_exited: specs.terminal_exited_action_spec,
	workspace_open: specs.workspace_open_action_spec,
	workspace_close: specs.workspace_close_action_spec,
	workspace_list: specs.workspace_list_action_spec,
	workspace_changed: specs.workspace_changed_action_spec,
} as const;
export interface ActionSpecs {
	heartbeat: typeof specs.heartbeat_action_spec;
	cancel: typeof specs.cancel_action_spec;
	ping: typeof specs.ping_action_spec;
	session_load: typeof specs.session_load_action_spec;
	filer_change: typeof specs.filer_change_action_spec;
	diskfile_update: typeof specs.diskfile_update_action_spec;
	diskfile_delete: typeof specs.diskfile_delete_action_spec;
	directory_create: typeof specs.directory_create_action_spec;
	completion_create: typeof specs.completion_create_action_spec;
	completion_progress: typeof specs.completion_progress_action_spec;
	toggle_main_menu: typeof specs.toggle_main_menu_action_spec;
	provider_load_status: typeof specs.provider_load_status_action_spec;
	provider_update_api_key: typeof specs.provider_update_api_key_action_spec;
	terminal_create: typeof specs.terminal_create_action_spec;
	terminal_data_send: typeof specs.terminal_data_send_action_spec;
	terminal_data: typeof specs.terminal_data_action_spec;
	terminal_resize: typeof specs.terminal_resize_action_spec;
	terminal_close: typeof specs.terminal_close_action_spec;
	terminal_exited: typeof specs.terminal_exited_action_spec;
	workspace_open: typeof specs.workspace_open_action_spec;
	workspace_close: typeof specs.workspace_close_action_spec;
	workspace_list: typeof specs.workspace_list_action_spec;
	workspace_changed: typeof specs.workspace_changed_action_spec;
}

export const action_specs: Array<ActionSpecUnion> = Object.values(ActionSpecs);

/**
 * Action parameter schemas indexed by method name.
 * These represent the input data for each action,
 * e.g. JSON-RPC request/notification params and local call arguments.
 */
export const ActionInputs = {
	heartbeat: specs.heartbeat_action_spec.input,
	cancel: specs.cancel_action_spec.input,
	ping: specs.ping_action_spec.input,
	session_load: specs.session_load_action_spec.input,
	filer_change: specs.filer_change_action_spec.input,
	diskfile_update: specs.diskfile_update_action_spec.input,
	diskfile_delete: specs.diskfile_delete_action_spec.input,
	directory_create: specs.directory_create_action_spec.input,
	completion_create: specs.completion_create_action_spec.input,
	completion_progress: specs.completion_progress_action_spec.input,
	toggle_main_menu: specs.toggle_main_menu_action_spec.input,
	provider_load_status: specs.provider_load_status_action_spec.input,
	provider_update_api_key: specs.provider_update_api_key_action_spec.input,
	terminal_create: specs.terminal_create_action_spec.input,
	terminal_data_send: specs.terminal_data_send_action_spec.input,
	terminal_data: specs.terminal_data_action_spec.input,
	terminal_resize: specs.terminal_resize_action_spec.input,
	terminal_close: specs.terminal_close_action_spec.input,
	terminal_exited: specs.terminal_exited_action_spec.input,
	workspace_open: specs.workspace_open_action_spec.input,
	workspace_close: specs.workspace_close_action_spec.input,
	workspace_list: specs.workspace_list_action_spec.input,
	workspace_changed: specs.workspace_changed_action_spec.input,
} as const;
export interface ActionInputs {
	heartbeat: z.infer<typeof specs.heartbeat_action_spec.input>;
	cancel: z.infer<typeof specs.cancel_action_spec.input>;
	ping: z.infer<typeof specs.ping_action_spec.input>;
	session_load: z.infer<typeof specs.session_load_action_spec.input>;
	filer_change: z.infer<typeof specs.filer_change_action_spec.input>;
	diskfile_update: z.infer<typeof specs.diskfile_update_action_spec.input>;
	diskfile_delete: z.infer<typeof specs.diskfile_delete_action_spec.input>;
	directory_create: z.infer<typeof specs.directory_create_action_spec.input>;
	completion_create: z.infer<typeof specs.completion_create_action_spec.input>;
	completion_progress: z.infer<typeof specs.completion_progress_action_spec.input>;
	toggle_main_menu: z.infer<typeof specs.toggle_main_menu_action_spec.input>;
	provider_load_status: z.infer<typeof specs.provider_load_status_action_spec.input>;
	provider_update_api_key: z.infer<typeof specs.provider_update_api_key_action_spec.input>;
	terminal_create: z.infer<typeof specs.terminal_create_action_spec.input>;
	terminal_data_send: z.infer<typeof specs.terminal_data_send_action_spec.input>;
	terminal_data: z.infer<typeof specs.terminal_data_action_spec.input>;
	terminal_resize: z.infer<typeof specs.terminal_resize_action_spec.input>;
	terminal_close: z.infer<typeof specs.terminal_close_action_spec.input>;
	terminal_exited: z.infer<typeof specs.terminal_exited_action_spec.input>;
	workspace_open: z.infer<typeof specs.workspace_open_action_spec.input>;
	workspace_close: z.infer<typeof specs.workspace_close_action_spec.input>;
	workspace_list: z.infer<typeof specs.workspace_list_action_spec.input>;
	workspace_changed: z.infer<typeof specs.workspace_changed_action_spec.input>;
}

/**
 * Action result schemas indexed by method name.
 * These represent the output data for each action,
 * e.g. JSON-RPC response results and local call return values.
 */
export const ActionOutputs = {
	heartbeat: specs.heartbeat_action_spec.output,
	cancel: specs.cancel_action_spec.output,
	ping: specs.ping_action_spec.output,
	session_load: specs.session_load_action_spec.output,
	filer_change: specs.filer_change_action_spec.output,
	diskfile_update: specs.diskfile_update_action_spec.output,
	diskfile_delete: specs.diskfile_delete_action_spec.output,
	directory_create: specs.directory_create_action_spec.output,
	completion_create: specs.completion_create_action_spec.output,
	completion_progress: specs.completion_progress_action_spec.output,
	toggle_main_menu: specs.toggle_main_menu_action_spec.output,
	provider_load_status: specs.provider_load_status_action_spec.output,
	provider_update_api_key: specs.provider_update_api_key_action_spec.output,
	terminal_create: specs.terminal_create_action_spec.output,
	terminal_data_send: specs.terminal_data_send_action_spec.output,
	terminal_data: specs.terminal_data_action_spec.output,
	terminal_resize: specs.terminal_resize_action_spec.output,
	terminal_close: specs.terminal_close_action_spec.output,
	terminal_exited: specs.terminal_exited_action_spec.output,
	workspace_open: specs.workspace_open_action_spec.output,
	workspace_close: specs.workspace_close_action_spec.output,
	workspace_list: specs.workspace_list_action_spec.output,
	workspace_changed: specs.workspace_changed_action_spec.output,
} as const;
export interface ActionOutputs {
	heartbeat: z.infer<typeof specs.heartbeat_action_spec.output>;
	cancel: z.infer<typeof specs.cancel_action_spec.output>;
	ping: z.infer<typeof specs.ping_action_spec.output>;
	session_load: z.infer<typeof specs.session_load_action_spec.output>;
	filer_change: z.infer<typeof specs.filer_change_action_spec.output>;
	diskfile_update: z.infer<typeof specs.diskfile_update_action_spec.output>;
	diskfile_delete: z.infer<typeof specs.diskfile_delete_action_spec.output>;
	directory_create: z.infer<typeof specs.directory_create_action_spec.output>;
	completion_create: z.infer<typeof specs.completion_create_action_spec.output>;
	completion_progress: z.infer<typeof specs.completion_progress_action_spec.output>;
	toggle_main_menu: z.infer<typeof specs.toggle_main_menu_action_spec.output>;
	provider_load_status: z.infer<typeof specs.provider_load_status_action_spec.output>;
	provider_update_api_key: z.infer<typeof specs.provider_update_api_key_action_spec.output>;
	terminal_create: z.infer<typeof specs.terminal_create_action_spec.output>;
	terminal_data_send: z.infer<typeof specs.terminal_data_send_action_spec.output>;
	terminal_data: z.infer<typeof specs.terminal_data_action_spec.output>;
	terminal_resize: z.infer<typeof specs.terminal_resize_action_spec.output>;
	terminal_close: z.infer<typeof specs.terminal_close_action_spec.output>;
	terminal_exited: z.infer<typeof specs.terminal_exited_action_spec.output>;
	workspace_open: z.infer<typeof specs.workspace_open_action_spec.output>;
	workspace_close: z.infer<typeof specs.workspace_close_action_spec.output>;
	workspace_list: z.infer<typeof specs.workspace_list_action_spec.output>;
	workspace_changed: z.infer<typeof specs.workspace_changed_action_spec.output>;
}

/**
 * Action event data types indexed by method name.
 * These represent the full discriminated union of all possible states
 * for each action's event data, properly typed with inputs and outputs.
 */
export interface ActionEventDatas {
	heartbeat: ActionEventRequestResponseData<
		'heartbeat',
		ActionInputs['heartbeat'],
		ActionOutputs['heartbeat']
	>;
	cancel: ActionEventRemoteNotificationData<'cancel', ActionInputs['cancel']>;
	ping: ActionEventRequestResponseData<'ping', ActionInputs['ping'], ActionOutputs['ping']>;
	session_load: ActionEventRequestResponseData<
		'session_load',
		ActionInputs['session_load'],
		ActionOutputs['session_load']
	>;
	filer_change: ActionEventRemoteNotificationData<'filer_change', ActionInputs['filer_change']>;
	diskfile_update: ActionEventRequestResponseData<
		'diskfile_update',
		ActionInputs['diskfile_update'],
		ActionOutputs['diskfile_update']
	>;
	diskfile_delete: ActionEventRequestResponseData<
		'diskfile_delete',
		ActionInputs['diskfile_delete'],
		ActionOutputs['diskfile_delete']
	>;
	directory_create: ActionEventRequestResponseData<
		'directory_create',
		ActionInputs['directory_create'],
		ActionOutputs['directory_create']
	>;
	completion_create: ActionEventRequestResponseData<
		'completion_create',
		ActionInputs['completion_create'],
		ActionOutputs['completion_create']
	>;
	completion_progress: ActionEventRemoteNotificationData<
		'completion_progress',
		ActionInputs['completion_progress']
	>;
	toggle_main_menu: ActionEventLocalCallData<
		'toggle_main_menu',
		ActionInputs['toggle_main_menu'],
		ActionOutputs['toggle_main_menu']
	>;
	provider_load_status: ActionEventRequestResponseData<
		'provider_load_status',
		ActionInputs['provider_load_status'],
		ActionOutputs['provider_load_status']
	>;
	provider_update_api_key: ActionEventRequestResponseData<
		'provider_update_api_key',
		ActionInputs['provider_update_api_key'],
		ActionOutputs['provider_update_api_key']
	>;
	terminal_create: ActionEventRequestResponseData<
		'terminal_create',
		ActionInputs['terminal_create'],
		ActionOutputs['terminal_create']
	>;
	terminal_data_send: ActionEventRequestResponseData<
		'terminal_data_send',
		ActionInputs['terminal_data_send'],
		ActionOutputs['terminal_data_send']
	>;
	terminal_data: ActionEventRemoteNotificationData<'terminal_data', ActionInputs['terminal_data']>;
	terminal_resize: ActionEventRequestResponseData<
		'terminal_resize',
		ActionInputs['terminal_resize'],
		ActionOutputs['terminal_resize']
	>;
	terminal_close: ActionEventRequestResponseData<
		'terminal_close',
		ActionInputs['terminal_close'],
		ActionOutputs['terminal_close']
	>;
	terminal_exited: ActionEventRemoteNotificationData<
		'terminal_exited',
		ActionInputs['terminal_exited']
	>;
	workspace_open: ActionEventRequestResponseData<
		'workspace_open',
		ActionInputs['workspace_open'],
		ActionOutputs['workspace_open']
	>;
	workspace_close: ActionEventRequestResponseData<
		'workspace_close',
		ActionInputs['workspace_close'],
		ActionOutputs['workspace_close']
	>;
	workspace_list: ActionEventRequestResponseData<
		'workspace_list',
		ActionInputs['workspace_list'],
		ActionOutputs['workspace_list']
	>;
	workspace_changed: ActionEventRemoteNotificationData<
		'workspace_changed',
		ActionInputs['workspace_changed']
	>;
}

// generated by src/lib/action_collections.gen.ts - DO NOT EDIT OR RISK LOST DATA
