// generated by src/lib/action_metatypes.gen.ts - DO NOT EDIT OR RISK LOST DATA

import {z} from 'zod';
import type {Result} from '@fuzdev/fuz_util/result.js';
import type {JsonrpcErrorObject} from '@fuzdev/fuz_app/http/jsonrpc.js';
import type {RpcClientCallOptions} from '@fuzdev/fuz_app/actions/rpc_client.js';
import type {ActionInputs, ActionOutputs} from './action_collections.js';

/**
 * All action method names. Request/response actions have two types per method.
 */
export const ActionMethod = z.enum([
	'ping',
	'session_load',
	'filer_change',
	'diskfile_update',
	'diskfile_delete',
	'directory_create',
	'completion_create',
	'completion_progress',
	'ollama_progress',
	'toggle_main_menu',
	'ollama_list',
	'ollama_ps',
	'ollama_show',
	'ollama_pull',
	'ollama_delete',
	'ollama_copy',
	'ollama_create',
	'ollama_unload',
	'provider_load_status',
	'provider_update_api_key',
	'terminal_create',
	'terminal_data_send',
	'terminal_data',
	'terminal_resize',
	'terminal_close',
	'terminal_exited',
	'workspace_open',
	'workspace_close',
	'workspace_list',
	'workspace_changed',
	'_test_emit_notifications',
	'_test_notification',
]);
export type ActionMethod = z.infer<typeof ActionMethod>;

/**
 * Names of all request_response actions.
 */
export const RequestResponseActionMethod = z.enum([
	'ping',
	'session_load',
	'diskfile_update',
	'diskfile_delete',
	'directory_create',
	'completion_create',
	'ollama_list',
	'ollama_ps',
	'ollama_show',
	'ollama_pull',
	'ollama_delete',
	'ollama_copy',
	'ollama_create',
	'ollama_unload',
	'provider_load_status',
	'provider_update_api_key',
	'terminal_create',
	'terminal_data_send',
	'terminal_resize',
	'terminal_close',
	'workspace_open',
	'workspace_close',
	'workspace_list',
	'_test_emit_notifications',
]);
export type RequestResponseActionMethod = z.infer<typeof RequestResponseActionMethod>;

/**
 * Names of all remote_notification actions.
 */
export const RemoteNotificationActionMethod = z.enum([
	'filer_change',
	'completion_progress',
	'ollama_progress',
	'terminal_data',
	'terminal_exited',
	'workspace_changed',
	'_test_notification',
]);
export type RemoteNotificationActionMethod = z.infer<typeof RemoteNotificationActionMethod>;

/**
 * Names of all local_call actions.
 */
export const LocalCallActionMethod = z.enum(['toggle_main_menu']);
export type LocalCallActionMethod = z.infer<typeof LocalCallActionMethod>;

/**
 * Names of all actions in the typed FrontendActionsApi surface — every spec the frontend may encounter (call, receive, or execute locally).
 */
export const FrontendActionMethod = z.enum([
	'ping',
	'session_load',
	'filer_change',
	'diskfile_update',
	'diskfile_delete',
	'directory_create',
	'completion_create',
	'completion_progress',
	'ollama_progress',
	'toggle_main_menu',
	'ollama_list',
	'ollama_ps',
	'ollama_show',
	'ollama_pull',
	'ollama_delete',
	'ollama_copy',
	'ollama_create',
	'ollama_unload',
	'provider_load_status',
	'provider_update_api_key',
	'terminal_create',
	'terminal_data_send',
	'terminal_data',
	'terminal_resize',
	'terminal_close',
	'terminal_exited',
	'workspace_open',
	'workspace_close',
	'workspace_list',
	'workspace_changed',
	'_test_emit_notifications',
	'_test_notification',
]);
export type FrontendActionMethod = z.infer<typeof FrontendActionMethod>;

/**
 * Names of all actions the backend may encounter — request_response and remote_notification (local_call is frontend-only).
 */
export const BackendActionMethod = z.enum([
	'ping',
	'session_load',
	'filer_change',
	'diskfile_update',
	'diskfile_delete',
	'directory_create',
	'completion_create',
	'completion_progress',
	'ollama_progress',
	'ollama_list',
	'ollama_ps',
	'ollama_show',
	'ollama_pull',
	'ollama_delete',
	'ollama_copy',
	'ollama_create',
	'ollama_unload',
	'provider_load_status',
	'provider_update_api_key',
	'terminal_create',
	'terminal_data_send',
	'terminal_data',
	'terminal_resize',
	'terminal_close',
	'terminal_exited',
	'workspace_open',
	'workspace_close',
	'workspace_list',
	'workspace_changed',
	'_test_emit_notifications',
	'_test_notification',
]);
export type BackendActionMethod = z.infer<typeof BackendActionMethod>;

/**
 * Names of request_response actions the frontend handles (initiator excludes frontend).
 */
export const FrontendRequestResponseMethod = z.enum(['ping']);
export type FrontendRequestResponseMethod = z.infer<typeof FrontendRequestResponseMethod>;

/**
 * Names of request_response actions the backend handles (initiator excludes backend).
 */
export const BackendRequestResponseMethod = z.enum([
	'ping',
	'session_load',
	'diskfile_update',
	'diskfile_delete',
	'directory_create',
	'completion_create',
	'ollama_list',
	'ollama_ps',
	'ollama_show',
	'ollama_pull',
	'ollama_delete',
	'ollama_copy',
	'ollama_create',
	'ollama_unload',
	'provider_load_status',
	'provider_update_api_key',
	'terminal_create',
	'terminal_data_send',
	'terminal_resize',
	'terminal_close',
	'workspace_open',
	'workspace_close',
	'workspace_list',
	'_test_emit_notifications',
]);
export type BackendRequestResponseMethod = z.infer<typeof BackendRequestResponseMethod>;

/**
 * Names of remote_notification actions exposed by the broadcast API (backend-initiated, excluding request-scoped progress notifications named by another action's `streams`).
 */
export const BroadcastActionMethod = z.enum([
	'filer_change',
	'terminal_data',
	'terminal_exited',
	'workspace_changed',
]);
export type BroadcastActionMethod = z.infer<typeof BroadcastActionMethod>;

/**
 * Typed dispatch surface for the frontend's RPC client. Symmetric counterpart
 * of `BackendActionsApi`. Async methods (request_response, remote_notification,
 * async local_call) return `Promise<Result<...>>` and accept an optional
 * `RpcClientCallOptions` second arg that threads `signal`, `transport_name`,
 * and `queue` through to the peer. Sync local_call methods return values
 * directly.
 */
export interface FrontendActionsApi {
	ping: (
		input?: void,
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['ping']}, {error: JsonrpcErrorObject}>>;
	session_load: (
		input?: void,
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['session_load']}, {error: JsonrpcErrorObject}>>;
	filer_change: (
		input: ActionInputs['filer_change'],
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['filer_change']}, {error: JsonrpcErrorObject}>>;
	diskfile_update: (
		input: ActionInputs['diskfile_update'],
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['diskfile_update']}, {error: JsonrpcErrorObject}>>;
	diskfile_delete: (
		input: ActionInputs['diskfile_delete'],
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['diskfile_delete']}, {error: JsonrpcErrorObject}>>;
	directory_create: (
		input: ActionInputs['directory_create'],
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['directory_create']}, {error: JsonrpcErrorObject}>>;
	completion_create: (
		input: ActionInputs['completion_create'],
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['completion_create']}, {error: JsonrpcErrorObject}>>;
	completion_progress: (
		input: ActionInputs['completion_progress'],
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['completion_progress']}, {error: JsonrpcErrorObject}>>;
	ollama_progress: (
		input: ActionInputs['ollama_progress'],
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['ollama_progress']}, {error: JsonrpcErrorObject}>>;
	toggle_main_menu: (input?: ActionInputs['toggle_main_menu']) => ActionOutputs['toggle_main_menu'];
	ollama_list: (
		input?: void,
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['ollama_list']}, {error: JsonrpcErrorObject}>>;
	ollama_ps: (
		input?: void,
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['ollama_ps']}, {error: JsonrpcErrorObject}>>;
	ollama_show: (
		input: ActionInputs['ollama_show'],
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['ollama_show']}, {error: JsonrpcErrorObject}>>;
	ollama_pull: (
		input: ActionInputs['ollama_pull'],
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['ollama_pull']}, {error: JsonrpcErrorObject}>>;
	ollama_delete: (
		input: ActionInputs['ollama_delete'],
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['ollama_delete']}, {error: JsonrpcErrorObject}>>;
	ollama_copy: (
		input: ActionInputs['ollama_copy'],
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['ollama_copy']}, {error: JsonrpcErrorObject}>>;
	ollama_create: (
		input: ActionInputs['ollama_create'],
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['ollama_create']}, {error: JsonrpcErrorObject}>>;
	ollama_unload: (
		input: ActionInputs['ollama_unload'],
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['ollama_unload']}, {error: JsonrpcErrorObject}>>;
	provider_load_status: (
		input: ActionInputs['provider_load_status'],
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['provider_load_status']}, {error: JsonrpcErrorObject}>>;
	provider_update_api_key: (
		input: ActionInputs['provider_update_api_key'],
		options?: RpcClientCallOptions,
	) => Promise<
		Result<{value: ActionOutputs['provider_update_api_key']}, {error: JsonrpcErrorObject}>
	>;
	terminal_create: (
		input: ActionInputs['terminal_create'],
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['terminal_create']}, {error: JsonrpcErrorObject}>>;
	terminal_data_send: (
		input: ActionInputs['terminal_data_send'],
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['terminal_data_send']}, {error: JsonrpcErrorObject}>>;
	terminal_data: (
		input: ActionInputs['terminal_data'],
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['terminal_data']}, {error: JsonrpcErrorObject}>>;
	terminal_resize: (
		input: ActionInputs['terminal_resize'],
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['terminal_resize']}, {error: JsonrpcErrorObject}>>;
	terminal_close: (
		input: ActionInputs['terminal_close'],
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['terminal_close']}, {error: JsonrpcErrorObject}>>;
	terminal_exited: (
		input: ActionInputs['terminal_exited'],
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['terminal_exited']}, {error: JsonrpcErrorObject}>>;
	workspace_open: (
		input: ActionInputs['workspace_open'],
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['workspace_open']}, {error: JsonrpcErrorObject}>>;
	workspace_close: (
		input: ActionInputs['workspace_close'],
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['workspace_close']}, {error: JsonrpcErrorObject}>>;
	workspace_list: (
		input?: void,
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['workspace_list']}, {error: JsonrpcErrorObject}>>;
	workspace_changed: (
		input: ActionInputs['workspace_changed'],
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['workspace_changed']}, {error: JsonrpcErrorObject}>>;
	_test_emit_notifications: (
		input: ActionInputs['_test_emit_notifications'],
		options?: RpcClientCallOptions,
	) => Promise<
		Result<{value: ActionOutputs['_test_emit_notifications']}, {error: JsonrpcErrorObject}>
	>;
	_test_notification: (
		input: ActionInputs['_test_notification'],
		options?: RpcClientCallOptions,
	) => Promise<Result<{value: ActionOutputs['_test_notification']}, {error: JsonrpcErrorObject}>>;
}

// generated by src/lib/action_metatypes.gen.ts - DO NOT EDIT OR RISK LOST DATA
