// generated by src/lib/frontend_action_types.gen.ts - DO NOT EDIT OR RISK LOST DATA

import type {ActionEvent} from './action_event.js';
import type {ActionOutputs} from './action_collections.js';

/**
 * Frontend action handlers organized by method and phase.
 * Generated using spec.initiator to determine valid phases:
 * - initiator: 'frontend' → send/execute phases
 * - initiator: 'backend' → receive phases
 * - initiator: 'both' → all valid phases
 */
export interface FrontendActionHandlers {
	ping?: {
		send_request?: (
			action_event: ActionEvent<'ping', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: ActionEvent<'ping', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: ActionEvent<'ping', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: ActionEvent<'ping', 'receive_error', 'handling'>,
		) => void | Promise<void>;
		receive_request?: (
			action_event: ActionEvent<'ping', 'receive_request', 'handling'>,
		) => ActionOutputs['ping'] | Promise<ActionOutputs['ping']>;
		send_response?: (
			action_event: ActionEvent<'ping', 'send_response', 'handling'>,
		) => void | Promise<void>;
	};
	session_load?: {
		send_request?: (
			action_event: ActionEvent<'session_load', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: ActionEvent<'session_load', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: ActionEvent<'session_load', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: ActionEvent<'session_load', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	filer_change?: {
		receive?: (
			action_event: ActionEvent<'filer_change', 'receive', 'handling'>,
		) => void | Promise<void>;
	};
	diskfile_update?: {
		send_request?: (
			action_event: ActionEvent<'diskfile_update', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: ActionEvent<'diskfile_update', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: ActionEvent<'diskfile_update', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: ActionEvent<'diskfile_update', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	diskfile_delete?: {
		send_request?: (
			action_event: ActionEvent<'diskfile_delete', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: ActionEvent<'diskfile_delete', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: ActionEvent<'diskfile_delete', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: ActionEvent<'diskfile_delete', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	directory_create?: {
		send_request?: (
			action_event: ActionEvent<'directory_create', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: ActionEvent<'directory_create', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: ActionEvent<'directory_create', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: ActionEvent<'directory_create', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	completion_create?: {
		send_request?: (
			action_event: ActionEvent<'completion_create', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: ActionEvent<'completion_create', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: ActionEvent<'completion_create', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: ActionEvent<'completion_create', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	completion_progress?: {
		receive?: (
			action_event: ActionEvent<'completion_progress', 'receive', 'handling'>,
		) => void | Promise<void>;
	};
	ollama_progress?: {
		receive?: (
			action_event: ActionEvent<'ollama_progress', 'receive', 'handling'>,
		) => void | Promise<void>;
	};
	toggle_main_menu?: {
		execute?: (
			action_event: ActionEvent<'toggle_main_menu', 'execute', 'handling'>,
		) => ActionOutputs['toggle_main_menu'];
	};
	ollama_list?: {
		send_request?: (
			action_event: ActionEvent<'ollama_list', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: ActionEvent<'ollama_list', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: ActionEvent<'ollama_list', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: ActionEvent<'ollama_list', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	ollama_ps?: {
		send_request?: (
			action_event: ActionEvent<'ollama_ps', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: ActionEvent<'ollama_ps', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: ActionEvent<'ollama_ps', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: ActionEvent<'ollama_ps', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	ollama_show?: {
		send_request?: (
			action_event: ActionEvent<'ollama_show', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: ActionEvent<'ollama_show', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: ActionEvent<'ollama_show', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: ActionEvent<'ollama_show', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	ollama_pull?: {
		send_request?: (
			action_event: ActionEvent<'ollama_pull', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: ActionEvent<'ollama_pull', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: ActionEvent<'ollama_pull', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: ActionEvent<'ollama_pull', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	ollama_delete?: {
		send_request?: (
			action_event: ActionEvent<'ollama_delete', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: ActionEvent<'ollama_delete', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: ActionEvent<'ollama_delete', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: ActionEvent<'ollama_delete', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	ollama_copy?: {
		send_request?: (
			action_event: ActionEvent<'ollama_copy', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: ActionEvent<'ollama_copy', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: ActionEvent<'ollama_copy', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: ActionEvent<'ollama_copy', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	ollama_create?: {
		send_request?: (
			action_event: ActionEvent<'ollama_create', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: ActionEvent<'ollama_create', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: ActionEvent<'ollama_create', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: ActionEvent<'ollama_create', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	ollama_unload?: {
		send_request?: (
			action_event: ActionEvent<'ollama_unload', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: ActionEvent<'ollama_unload', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: ActionEvent<'ollama_unload', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: ActionEvent<'ollama_unload', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	provider_load_status?: {
		send_request?: (
			action_event: ActionEvent<'provider_load_status', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: ActionEvent<'provider_load_status', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: ActionEvent<'provider_load_status', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: ActionEvent<'provider_load_status', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	provider_update_api_key?: {
		send_request?: (
			action_event: ActionEvent<'provider_update_api_key', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: ActionEvent<'provider_update_api_key', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: ActionEvent<'provider_update_api_key', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: ActionEvent<'provider_update_api_key', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	terminal_create?: {
		send_request?: (
			action_event: ActionEvent<'terminal_create', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: ActionEvent<'terminal_create', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: ActionEvent<'terminal_create', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: ActionEvent<'terminal_create', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	terminal_data_send?: {
		send_request?: (
			action_event: ActionEvent<'terminal_data_send', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: ActionEvent<'terminal_data_send', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: ActionEvent<'terminal_data_send', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: ActionEvent<'terminal_data_send', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	terminal_data?: {
		receive?: (
			action_event: ActionEvent<'terminal_data', 'receive', 'handling'>,
		) => void | Promise<void>;
	};
	terminal_resize?: {
		send_request?: (
			action_event: ActionEvent<'terminal_resize', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: ActionEvent<'terminal_resize', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: ActionEvent<'terminal_resize', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: ActionEvent<'terminal_resize', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	terminal_close?: {
		send_request?: (
			action_event: ActionEvent<'terminal_close', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: ActionEvent<'terminal_close', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: ActionEvent<'terminal_close', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: ActionEvent<'terminal_close', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	terminal_exited?: {
		receive?: (
			action_event: ActionEvent<'terminal_exited', 'receive', 'handling'>,
		) => void | Promise<void>;
	};
	workspace_open?: {
		send_request?: (
			action_event: ActionEvent<'workspace_open', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: ActionEvent<'workspace_open', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: ActionEvent<'workspace_open', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: ActionEvent<'workspace_open', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	workspace_close?: {
		send_request?: (
			action_event: ActionEvent<'workspace_close', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: ActionEvent<'workspace_close', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: ActionEvent<'workspace_close', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: ActionEvent<'workspace_close', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	workspace_list?: {
		send_request?: (
			action_event: ActionEvent<'workspace_list', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: ActionEvent<'workspace_list', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: ActionEvent<'workspace_list', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: ActionEvent<'workspace_list', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	workspace_changed?: {
		receive?: (
			action_event: ActionEvent<'workspace_changed', 'receive', 'handling'>,
		) => void | Promise<void>;
	};
}

// generated by src/lib/frontend_action_types.gen.ts - DO NOT EDIT OR RISK LOST DATA
