// generated by src/lib/frontend_action_types.gen.ts - DO NOT EDIT OR RISK LOST DATA

import type {ActionEvent} from '@fuzdev/fuz_app/actions/action_event.js';
import type {ActionEventPhase} from '@fuzdev/fuz_app/actions/action_spec.js';
import type {ActionEventStep} from '@fuzdev/fuz_app/actions/action_event_types.js';
import type {ActionEventDatas, ActionOutputs} from './action_collections.js';

import type {ActionMethod} from './action_metatypes.js';

/** ActionEvent narrowed with zzz's generated ActionEventDatas for typed input/output. */
type TypedActionEvent<
	TMethod extends ActionMethod,
	TPhase extends ActionEventPhase,
	TStep extends ActionEventStep,
> = ActionEvent<TMethod, TPhase, TStep> & {readonly data: ActionEventDatas[TMethod]};

/**
 * Frontend action handlers organized by method and phase.
 * Generated using spec.initiator to determine valid phases:
 * - initiator: 'frontend' → send/execute phases
 * - initiator: 'backend' → receive phases
 * - initiator: 'both' → all valid phases
 */
export interface FrontendActionHandlers {
	ping?: {
		send_request?: (
			action_event: TypedActionEvent<'ping', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: TypedActionEvent<'ping', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: TypedActionEvent<'ping', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: TypedActionEvent<'ping', 'receive_error', 'handling'>,
		) => void | Promise<void>;
		receive_request?: (
			action_event: TypedActionEvent<'ping', 'receive_request', 'handling'>,
		) => ActionOutputs['ping'] | Promise<ActionOutputs['ping']>;
		send_response?: (
			action_event: TypedActionEvent<'ping', 'send_response', 'handling'>,
		) => void | Promise<void>;
	};
	session_load?: {
		send_request?: (
			action_event: TypedActionEvent<'session_load', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: TypedActionEvent<'session_load', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: TypedActionEvent<'session_load', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: TypedActionEvent<'session_load', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	filer_change?: {
		receive?: (
			action_event: TypedActionEvent<'filer_change', 'receive', 'handling'>,
		) => void | Promise<void>;
	};
	diskfile_update?: {
		send_request?: (
			action_event: TypedActionEvent<'diskfile_update', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: TypedActionEvent<'diskfile_update', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: TypedActionEvent<'diskfile_update', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: TypedActionEvent<'diskfile_update', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	diskfile_delete?: {
		send_request?: (
			action_event: TypedActionEvent<'diskfile_delete', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: TypedActionEvent<'diskfile_delete', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: TypedActionEvent<'diskfile_delete', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: TypedActionEvent<'diskfile_delete', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	directory_create?: {
		send_request?: (
			action_event: TypedActionEvent<'directory_create', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: TypedActionEvent<'directory_create', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: TypedActionEvent<'directory_create', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: TypedActionEvent<'directory_create', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	completion_create?: {
		send_request?: (
			action_event: TypedActionEvent<'completion_create', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: TypedActionEvent<'completion_create', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: TypedActionEvent<'completion_create', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: TypedActionEvent<'completion_create', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	completion_progress?: {
		receive?: (
			action_event: TypedActionEvent<'completion_progress', 'receive', 'handling'>,
		) => void | Promise<void>;
	};
	ollama_progress?: {
		receive?: (
			action_event: TypedActionEvent<'ollama_progress', 'receive', 'handling'>,
		) => void | Promise<void>;
	};
	toggle_main_menu?: {
		execute?: (
			action_event: TypedActionEvent<'toggle_main_menu', 'execute', 'handling'>,
		) => ActionOutputs['toggle_main_menu'];
	};
	ollama_list?: {
		send_request?: (
			action_event: TypedActionEvent<'ollama_list', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: TypedActionEvent<'ollama_list', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: TypedActionEvent<'ollama_list', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: TypedActionEvent<'ollama_list', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	ollama_ps?: {
		send_request?: (
			action_event: TypedActionEvent<'ollama_ps', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: TypedActionEvent<'ollama_ps', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: TypedActionEvent<'ollama_ps', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: TypedActionEvent<'ollama_ps', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	ollama_show?: {
		send_request?: (
			action_event: TypedActionEvent<'ollama_show', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: TypedActionEvent<'ollama_show', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: TypedActionEvent<'ollama_show', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: TypedActionEvent<'ollama_show', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	ollama_pull?: {
		send_request?: (
			action_event: TypedActionEvent<'ollama_pull', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: TypedActionEvent<'ollama_pull', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: TypedActionEvent<'ollama_pull', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: TypedActionEvent<'ollama_pull', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	ollama_delete?: {
		send_request?: (
			action_event: TypedActionEvent<'ollama_delete', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: TypedActionEvent<'ollama_delete', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: TypedActionEvent<'ollama_delete', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: TypedActionEvent<'ollama_delete', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	ollama_copy?: {
		send_request?: (
			action_event: TypedActionEvent<'ollama_copy', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: TypedActionEvent<'ollama_copy', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: TypedActionEvent<'ollama_copy', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: TypedActionEvent<'ollama_copy', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	ollama_create?: {
		send_request?: (
			action_event: TypedActionEvent<'ollama_create', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: TypedActionEvent<'ollama_create', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: TypedActionEvent<'ollama_create', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: TypedActionEvent<'ollama_create', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	ollama_unload?: {
		send_request?: (
			action_event: TypedActionEvent<'ollama_unload', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: TypedActionEvent<'ollama_unload', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: TypedActionEvent<'ollama_unload', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: TypedActionEvent<'ollama_unload', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	provider_load_status?: {
		send_request?: (
			action_event: TypedActionEvent<'provider_load_status', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: TypedActionEvent<'provider_load_status', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: TypedActionEvent<'provider_load_status', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: TypedActionEvent<'provider_load_status', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	provider_update_api_key?: {
		send_request?: (
			action_event: TypedActionEvent<'provider_update_api_key', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: TypedActionEvent<'provider_update_api_key', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: TypedActionEvent<'provider_update_api_key', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: TypedActionEvent<'provider_update_api_key', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	terminal_create?: {
		send_request?: (
			action_event: TypedActionEvent<'terminal_create', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: TypedActionEvent<'terminal_create', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: TypedActionEvent<'terminal_create', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: TypedActionEvent<'terminal_create', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	terminal_data_send?: {
		send_request?: (
			action_event: TypedActionEvent<'terminal_data_send', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: TypedActionEvent<'terminal_data_send', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: TypedActionEvent<'terminal_data_send', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: TypedActionEvent<'terminal_data_send', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	terminal_data?: {
		receive?: (
			action_event: TypedActionEvent<'terminal_data', 'receive', 'handling'>,
		) => void | Promise<void>;
	};
	terminal_resize?: {
		send_request?: (
			action_event: TypedActionEvent<'terminal_resize', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: TypedActionEvent<'terminal_resize', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: TypedActionEvent<'terminal_resize', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: TypedActionEvent<'terminal_resize', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	terminal_close?: {
		send_request?: (
			action_event: TypedActionEvent<'terminal_close', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: TypedActionEvent<'terminal_close', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: TypedActionEvent<'terminal_close', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: TypedActionEvent<'terminal_close', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	terminal_exited?: {
		receive?: (
			action_event: TypedActionEvent<'terminal_exited', 'receive', 'handling'>,
		) => void | Promise<void>;
	};
	workspace_open?: {
		send_request?: (
			action_event: TypedActionEvent<'workspace_open', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: TypedActionEvent<'workspace_open', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: TypedActionEvent<'workspace_open', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: TypedActionEvent<'workspace_open', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	workspace_close?: {
		send_request?: (
			action_event: TypedActionEvent<'workspace_close', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: TypedActionEvent<'workspace_close', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: TypedActionEvent<'workspace_close', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: TypedActionEvent<'workspace_close', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	workspace_list?: {
		send_request?: (
			action_event: TypedActionEvent<'workspace_list', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: TypedActionEvent<'workspace_list', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: TypedActionEvent<'workspace_list', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: TypedActionEvent<'workspace_list', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	workspace_changed?: {
		receive?: (
			action_event: TypedActionEvent<'workspace_changed', 'receive', 'handling'>,
		) => void | Promise<void>;
	};
	_test_emit_notifications?: {
		send_request?: (
			action_event: TypedActionEvent<'_test_emit_notifications', 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: TypedActionEvent<'_test_emit_notifications', 'receive_response', 'handling'>,
		) => void | Promise<void>;
		send_error?: (
			action_event: TypedActionEvent<'_test_emit_notifications', 'send_error', 'handling'>,
		) => void | Promise<void>;
		receive_error?: (
			action_event: TypedActionEvent<'_test_emit_notifications', 'receive_error', 'handling'>,
		) => void | Promise<void>;
	};
	_test_notification?: {
		receive?: (
			action_event: TypedActionEvent<'_test_notification', 'receive', 'handling'>,
		) => void | Promise<void>;
	};
}

// generated by src/lib/frontend_action_types.gen.ts - DO NOT EDIT OR RISK LOST DATA
