import type { Gen } from '@fuzdev/gro/gen.ts';
import { is_protocol_action_method } from '@fuzdev/fuz_app/actions/action_codegen.ts';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { all_action_specs } from './action_specs.ts';

/**
 * zzz's own action specs, excluding the fuz_app protocol actions
 * (`heartbeat` / `cancel`) that `all_action_specs` folds in for dispatch.
 */
const domain_specs = all_action_specs.filter((spec) => !is_protocol_action_method(spec.method));

/**
 * Generates `docs/reference.md` — the action-spec and cell-class reference
 * lists — directly from `action_specs.ts` and `cell_classes.ts`, so the
 * reference can't drift from source. `gro check` (gen --check) fails if it
 * goes stale.
 *
 * The cell registry is read as text rather than imported because the
 * `*.svelte.ts` cell modules use runes (`$state`) that aren't available in
 * the plain `gro gen` runtime.
 *
 * @nodocs
 */
export const gen: Gen = ({ origin_path }) => {
	const cell_names = parse_cell_class_names(
		readFileSync(join(dirname(origin_path), 'cell_classes.ts'), 'utf8')
	);

	const content = `<!-- generated by ${origin_path} - DO NOT EDIT -->

# Reference

Generated from \`action_specs.ts\` and \`cell_classes.ts\` by \`reference.gen.ts\`.
Run \`gro gen\` to refresh it; \`gro check\` fails if it drifts. Don't edit by hand.

## Action specs (${domain_specs.length})

The fuz_app protocol actions \`heartbeat\` and \`cancel\` are dispatched too but
omitted here — they belong to the shared runtime, not zzz.

${to_action_bullets(domain_specs)}

## Cell classes (${cell_names.length})

${cell_names.map((name) => `\`${name}\``).join(', ')}
`;

	return { filename: '../../docs/reference.md', content };
};

type Action_Auth = {
	account: string;
	actor: string;
	roles?: ReadonlyArray<string>;
	credential_types?: ReadonlyArray<string>;
} | null;

/** Render an action's four-axis auth record as a compact cell string. */
const format_auth = (auth: Action_Auth): string => {
	if (!auth) return 'public';
	const parts = [`account=${auth.account}`, `actor=${auth.actor}`];
	if (auth.roles && auth.roles.length) parts.push(`roles=${auth.roles.join('|')}`);
	if (auth.credential_types && auth.credential_types.length) {
		parts.push(`creds=${auth.credential_types.join('|')}`);
	}
	return parts.join(', ');
};

/** Flatten a value to a single line for a Markdown bullet. */
const bullet_text = (value: string): string => value.replace(/\n/g, ' ');

const to_action_bullets = (specs: typeof all_action_specs): string =>
	[...specs]
		.sort((a, b) => a.method.localeCompare(b.method))
		.map((spec) => {
			const desc = bullet_text(spec.description).replace(/\.\s*$/, '');
			return `- \`${spec.method}\` — ${desc}. Kind: ${spec.kind}. Initiator: ${spec.initiator}. Auth: ${bullet_text(format_auth(spec.auth))}`;
		})
		.join('\n');

/** Extract the registered cell class names from `cell_classes.ts` source text. */
const parse_cell_class_names = (source: string): Array<string> => {
	const block = /export const cell_classes = \{([\s\S]*?)\}/.exec(source);
	const names = (block?.[1] ?? '').match(/[A-Z][A-Za-z0-9_]*/g) ?? [];
	return [...new Set(names)].sort((a, b) => a.localeCompare(b));
};
