/**
 * Cross-process integration suite for zzz auth surfaces.
 *
 * Wraps the fuz_app standard suites that are cross-process-safe against
 * a spawned backend handle injected by {@link ../cross_backend/global_setup.ts}.
 * The backend is spawned + bootstrapped once per vitest project via
 * `bootstrap_backend`; each suite below opens a fresh per-test fixture
 * via `default_cross_process_setup` (sign up + log in a fresh account
 * per test, mint an API token for both session + bearer credentials).
 *
 * **Suites included** — the cross-process-safe subset of the standard
 * bundle. `describe_standard_tests` itself is not called because it
 * also runs `describe_rate_limiting_tests`, which builds a fresh
 * `TestApp` per test (in-process only, no spawned-backend path):
 *
 * - {@link describe_standard_integration_tests}
 * - {@link describe_standard_admin_integration_tests} (gated on `roles`
 *   from `create_role_schema()`)
 * - {@link describe_round_trip_validation}
 * - {@link describe_rpc_round_trip_tests}
 * - {@link describe_data_exposure_tests}
 *
 * **Suites omitted** (and why):
 *
 * - `describe_rate_limiting_tests` — bypasses `setup_test` to inject
 *   per-test rate-limiter overrides through a fresh `TestApp`; the
 *   spawned-binary path can't accept those overrides.
 * - `describe_audit_completeness_tests` — Tier 2 by the
 *   cross-backend-integration quest design; the suite reaches into
 *   FK-structural introspection that only the in-process backend
 *   exposes.
 * - `describe_bootstrap_success_tests` — bootstrap is one-shot; the
 *   `globalSetup` already consumed it.
 *
 * **Surface source — inline TS, not the on-disk snapshot.** Cross-process
 * tests construct the `AppSurfaceSpec` in TS via the same builder that
 * fuz_app's in-process attack-surface tests use (`create_zzz_app_surface_spec`).
 * The cross-process-ness lives in the transport (`FetchTransport` against
 * the spawned binary) and the per-test fixture (`default_cross_process_setup`),
 * not in the schema source. The on-disk `auth_attack_surface.json` is an
 * observability artifact — generated by `gro gen` for human inspection +
 * gen-time drift detection — and is not consumed by this suite at runtime.
 *
 * @module
 */

import {inject} from 'vitest';
import {
	default_cross_process_setup,
	reconstruct_bootstrapped_handle,
} from '@fuzdev/fuz_app/testing/cross_backend/setup.js';
import {describe_standard_integration_tests} from '@fuzdev/fuz_app/testing/integration.js';
import {describe_standard_admin_integration_tests} from '@fuzdev/fuz_app/testing/admin_integration.js';
import {describe_round_trip_validation} from '@fuzdev/fuz_app/testing/round_trip.js';
import {describe_rpc_round_trip_tests} from '@fuzdev/fuz_app/testing/rpc_round_trip.js';
import {describe_data_exposure_tests} from '@fuzdev/fuz_app/testing/data_exposure.js';
import {fuz_session_config} from '@fuzdev/fuz_app/auth/session_cookie.js';
import {create_role_schema, ROLE_ADMIN} from '@fuzdev/fuz_app/auth/role_schema.js';
import {stub} from '@fuzdev/fuz_app/testing/stubs.js';
import type {AppServerContext} from '@fuzdev/fuz_app/server/app_server.js';
import type {RpcEndpointSpec} from '@fuzdev/fuz_app/http/surface.js';

import './cross_test_types.js';
import {build_rpc_endpoint_specs} from '$lib/server/zzz_route_specs.js';
import {create_zzz_app_surface_spec} from '../server/routes/auth_attack_surface_helpers.js';

const handle = reconstruct_bootstrapped_handle(inject('backend_handle'));
// Grant `ROLE_ADMIN` to every per-test signup account via the production
// offer/accept consent flow so the admin-observer tests in
// `describe_standard_integration_tests` (signup invite edge cases) and
// `describe_standard_admin_integration_tests` (invite/role-grant flows)
// can drive admin-gated RPC methods through `fixture.create_session_headers()`.
// Cost: ~2 RPCs × ~30-50ms per test. Cross-process analog of the in-process
// `extra_keeper_roles: [ROLE_ADMIN]` wiring on `default_in_process_suite_options`.
const setup_test = default_cross_process_setup(handle, {extra_keeper_roles: [ROLE_ADMIN]});
const surface_source = create_zzz_app_surface_spec();
const {capabilities} = handle.config;
// Pass the factory form so the suites' setup-time resolution
// (`resolve_rpc_endpoints_for_setup` against a stub ctx) reads
// `path` + `spec.method` names. Handler closures are never invoked
// across the process boundary — live dispatch happens in the spawned
// binary, which wires its own `build_rpc_endpoint_specs` against the
// real `Backend`. The `stub` placeholder satisfies the `ZzzRpcDeps`
// shape without touching the real backend; throwing-stub access is
// safe because `create_zzz_action_handlers` only closes over `backend`
// at construction (no property reads).
const zzz_rpc_stub_deps = {backend: stub};
const rpc_endpoints = (ctx: AppServerContext): Array<RpcEndpointSpec> =>
	build_rpc_endpoint_specs(ctx, zzz_rpc_stub_deps);
const session_options = fuz_session_config;
// Built-in roles only — zzz registers no additional role specs today.
// When zzz introduces app-defined roles (e.g. a per-workspace
// collaborator role), thread the registry through `create_role_schema`
// here so the admin suite picks up grant-path coverage.
const roles = create_role_schema([]);

describe_standard_integration_tests({
	setup_test,
	surface_source,
	capabilities,
	session_options,
	rpc_endpoints,
});

describe_standard_admin_integration_tests({
	setup_test,
	surface_source,
	capabilities,
	session_options,
	rpc_endpoints,
	roles,
});

describe_round_trip_validation({
	setup_test,
	surface_source,
	capabilities,
});

describe_rpc_round_trip_tests({
	setup_test,
	surface_source,
	capabilities,
	session_options,
	rpc_endpoints,
});

describe_data_exposure_tests({
	setup_test,
	surface_source,
	capabilities,
});
