// generated by src/lib/server/backend_action_types.gen.ts - DO NOT EDIT OR RISK LOST DATA

import type {ZzzHandlerContext} from './zzz_action_handlers.js';
import type {ActionSpecUnion} from '@fuzdev/fuz_app/actions/action_spec.js';
import type {ActionInputs, ActionOutputs} from '../action_collections.js';
import * as specs from '../action_specs.js';
import type {BackendRequestResponseMethod} from '../action_metatypes.js';

/**
 * Typed dispatch surface for backend-initiated calls. Symmetric counterpart
 * of `FrontendActionsApi`. Today exposes broadcast-style `remote_notification`
 * methods (1→N fan-out via `create_broadcast_api`); request-scoped streaming
 * goes through `ctx.notify` inside a handler — it's socket-scoped, not a
 * broadcast. Will widen when a second backend runtime constructor (targeted
 * send, backend-initiated request_response) lands.
 */
export interface BackendActionsApi {
	filer_change: (input: ActionInputs['filer_change']) => Promise<void>;
	terminal_data: (input: ActionInputs['terminal_data']) => Promise<void>;
	terminal_exited: (input: ActionInputs['terminal_exited']) => Promise<void>;
	workspace_changed: (input: ActionInputs['workspace_changed']) => Promise<void>;
}

export const broadcast_action_specs: ReadonlyArray<ActionSpecUnion> = [
	specs.filer_change_action_spec,
	specs.terminal_data_action_spec,
	specs.terminal_exited_action_spec,
	specs.workspace_changed_action_spec,
];

/**
 * Typed handler map for request_response actions the backend handles.
 * One entry per BackendRequestResponseMethod; each handler receives the typed input
 * and returns the typed output (sync or async).
 */
export type BackendActionHandlers = {
	[K in BackendRequestResponseMethod]: (
		input: ActionInputs[K],
		ctx: ZzzHandlerContext,
	) => ActionOutputs[K] | Promise<ActionOutputs[K]>;
};

// generated by src/lib/server/backend_action_types.gen.ts - DO NOT EDIT OR RISK LOST DATA
